using System;
using System.Collections.Generic;

namespace DatabaseFirst.Models
{
    public partial class HtDataParamTmultct
    {
        public decimal HtDataParamTmultctid { get; set; }
        public string? Cjid { get; set; }
        public int? MeterId { get; set; }
        public int? Dtrid { get; set; }
        public int? CommandId { get; set; }
        public string? Rtc { get; set; }
        public decimal? CurrentRphase { get; set; }
        public decimal? CurrentYphase { get; set; }
        public decimal? CurrentBphase { get; set; }
        public string? LoadLimitFunctionStatus { get; set; }
        public string? PowerAlert { get; set; }
        public string? SrlcdoorsStatus { get; set; }
        public DateTimeOffset? SrlcddoorStatusTs { get; set; }
        public string? OilLevel { get; set; }
        public string? SrlcoilLevel { get; set; }
        public decimal? SrlcoilTemperature { get; set; }
        public decimal? SrlcsurfaceTemperature { get; set; }
        public decimal? Srlcambtemperature { get; set; }
        public string? RelayAlert { get; set; }
        public decimal? AvgCurrentIr { get; set; }
        public decimal? AvgCurrentIy { get; set; }
        public decimal? AvgCurrentIb { get; set; }
        public decimal? L1voltageVrn { get; set; }
        public decimal? AvgVoltageVrn { get; set; }
        public decimal? L2voltageVyn { get; set; }
        public decimal? AvgVoltageVyn { get; set; }
        public decimal? L3voltageVbn { get; set; }
        public decimal? L1signedPowerFactorRphase { get; set; }
        public decimal? AvgVoltageVbn { get; set; }
        public decimal? L2signedPowerFactorYphase { get; set; }
        public decimal? L3signedPowerFactorBphase { get; set; }
        public decimal? BlockEnergyWhImport { get; set; }
        public decimal? SignedThreePhasePowerFactorPf { get; set; }
        public decimal? BlockEnergyVahImport { get; set; }
        public decimal? BlockEnergyWhExport { get; set; }
        public decimal? Frequency { get; set; }
        public decimal? BlockEnergyVahExport { get; set; }
        public decimal? ApparentPowerkVa { get; set; }
        public decimal? BlockEnergykvarhLagIimport { get; set; }
        public decimal? BlockEnergykvarhLagIiexport { get; set; }
        public decimal? SignedActivePowerkW { get; set; }
        public decimal? BlockEnergykvarhLeadIiiimport { get; set; }
        public decimal? SignedReactivePowerkvar { get; set; }
        public decimal? BlockEnergykvarhLeadIvexport { get; set; }
        public int? NoOfPowerFailures { get; set; }
        public string? CommunicationModemStatusByte { get; set; }
        public long? CumulativePowerFailureDurationMin { get; set; }
        public string? GsmrssisignalStrength { get; set; }
        public long? CumulativeTamperCount { get; set; }
        public long? CumulativeBillingCount { get; set; }
        public long? CumulativeProgrammingCount { get; set; }
        public string? BillingDateLastReset { get; set; }
        public decimal? CumulativeEnergykWhimport { get; set; }
        public decimal? CumulativeEnergykWhexport { get; set; }
        public decimal? CumulativeEnergykvarhLagIimport { get; set; }
        public decimal? CumulativeEnergykvarhLagIiexport { get; set; }
        public long? EventCounterforVoltagerelatedEvents { get; set; }
        public decimal? CumulativeEnergykvarhLeadIiiimport { get; set; }
        public long? EventCounterforCurrentRelatedEvents { get; set; }
        public decimal? CumulativeEnergykvarhLeadIvexport { get; set; }
        public long? EventCounterforPowerRelatedEvents { get; set; }
        public long? EventCounterforTransactionRelatedEvents { get; set; }
        public decimal? CumulativeEnergykVahimport { get; set; }
        public long? EventCounterforOtherEvents { get; set; }
        public decimal? CumulativeEnergykVahexport { get; set; }
        public long? EventCounterforNonRolloverEvents { get; set; }
        public long? EventCounterforControlEvents { get; set; }
        public decimal? MdkWimport { get; set; }
        public long? EventCounterForTmurelatedEvents { get; set; }
        public string? MdkWimportTimeStamp { get; set; }
        public decimal? MdkVaimport { get; set; }
        public string? MdkVaimportTimeStamp { get; set; }
        public string? MaximumDemandkWdtexport { get; set; }
        public decimal? MaximumDemandkWexport { get; set; }
        public decimal? MaximumDemandkVaexport { get; set; }
        public string? MaximumDemandkVadtexport { get; set; }
        public decimal? CumulativeFundamentalEnergyKwhImport { get; set; }
        public decimal? CumulativeFundamentalEnergykWhExport { get; set; }
        public decimal? NeutralCurrent { get; set; }
        public string? RelayStatusRphase { get; set; }
        public string? RelayStatusYphase { get; set; }
        public string? RelayStatusBphase { get; set; }
        public string? RelayStatusNeutral { get; set; }
        public string? Value { get; set; }
        public decimal? LoadLimitValueinkW { get; set; }
        public decimal? ThdrphaseCurrent { get; set; }
        public decimal? ThdyphaseCurrent { get; set; }
        public decimal? ThdbphaseCurrent { get; set; }
        public decimal? ThdrphaseVoltage { get; set; }
        public decimal? ThdyphaseVoltage { get; set; }
        public decimal? ThdbphaseVoltage { get; set; }
        public string? MeterSerialNumber { get; set; }
        public string? Success { get; set; }
        public string? DeviceId { get; set; }
        public string? ManufacturerName { get; set; }
        public string? ActiveFirmwareIdentifier { get; set; }
        public string? MeterType3P3w3p4w { get; set; }
        public string? Category { get; set; }
        public string? CurrentRating { get; set; }
        public string? MeterYearofManufacture { get; set; }
        public int? TransformerRatioCurrentNumerator { get; set; }
        public int? TransformerRatioVoltageNumerator { get; set; }
        public DateTimeOffset? BillingDate { get; set; }
        public string? SystemPowerFactorForBillingPeriod { get; set; }
        public string? CumulativeEnergykWhForTz1 { get; set; }
        public string? CumulativeEnergykWhForTz2 { get; set; }
        public string? CumulativeEnergykWhForTz3 { get; set; }
        public string? CumulativeEnergykWhForTz4 { get; set; }
        public string? CumulativeEnergykWhForTz5 { get; set; }
        public string? CumulativeEnergykWhForTz6 { get; set; }
        public string? CumulativeEnergykWhForTz7 { get; set; }
        public string? CumulativeEnergykWhForTz8 { get; set; }
        public string? CumulativeEnergykVahForTz1 { get; set; }
        public string? CumulativeEnergykVahForTz2 { get; set; }
        public string? CumulativeEnergykVahForTz3 { get; set; }
        public string? CumulativeEnergykVahForTz4 { get; set; }
        public string? CumulativeEnergykVahForTz5 { get; set; }
        public string? CumulativeEnergykVahForTz6 { get; set; }
        public string? CumulativeEnergykVahForTz7 { get; set; }
        public string? CumulativeEnergykVahForTz8 { get; set; }
        public decimal? Mdkwt1 { get; set; }
        public string? Mdkwt1timeStamp { get; set; }
        public decimal? Mdkwt2 { get; set; }
        public string? Mdkwt2timeStamp { get; set; }
        public decimal? Mdkwt3 { get; set; }
        public string? Mdkwt3timeStamp { get; set; }
        public decimal? Mdkwt4 { get; set; }
        public string? Mdkwt4timeStamp { get; set; }
        public decimal? Mdkwt5 { get; set; }
        public string? Mdkwt5timeStamp { get; set; }
        public decimal? Mdkwt6 { get; set; }
        public string? Mdkwt6timeStamp { get; set; }
        public decimal? Mdkwt7 { get; set; }
        public string? Mdkwt7timeStamp { get; set; }
        public decimal? Mdkwt8 { get; set; }
        public string? Mdkwt8timeStamp { get; set; }
        public decimal? Mdkvat1 { get; set; }
        public string? Mdkvat1timeStamp { get; set; }
        public decimal? Mdkvat2 { get; set; }
        public string? Mdkvat2timeStamp { get; set; }
        public decimal? Mdkvat3 { get; set; }
        public string? Mdkvat3timeStamp { get; set; }
        public decimal? Mdkvat4 { get; set; }
        public string? Mdkvat4timeStamp { get; set; }
        public decimal? Mdkvat5 { get; set; }
        public string? Mdkvat5timeStamp { get; set; }
        public decimal? Mdkvat6 { get; set; }
        public string? Mdkvat6timeStamp { get; set; }
        public decimal? Mdkvat7 { get; set; }
        public string? Mdkvat7timeStamp { get; set; }
        public decimal? Mdkvat8 { get; set; }
        public string? Mdkvat8timeStamp { get; set; }
        public long? BillingPowerOnDurationInMinutes { get; set; }
        public string? PushSetupId { get; set; }
        public decimal? CumEnergykVarhLgImport { get; set; }
        public decimal? CumEnergykVarhLdImport { get; set; }
        public string? EmeventStatusWord { get; set; }
        public string? EmeventCode { get; set; }
        public string? RphasePotential { get; set; }
        public string? RphasePotentialTs { get; set; }
        public string? YphasePotential { get; set; }
        public string? YphasePotentialTs { get; set; }
        public string? BphasePotential { get; set; }
        public string? BphasePotentialTs { get; set; }
        public string? OverVoltagePhase { get; set; }
        public string? OverVoltagePhaseTs { get; set; }
        public string? LowVoltagePhase { get; set; }
        public string? LowVoltagePhaseTs { get; set; }
        public string? VoltageUnbalance { get; set; }
        public string? VoltageUnbalanceTs { get; set; }
        public string? RphaseCtReverse { get; set; }
        public string? RphaseCtReverseTs { get; set; }
        public string? YphaseCtReverse { get; set; }
        public string? YphaseCtReverseTs { get; set; }
        public string? BphaseCtReverse { get; set; }
        public string? BphaseCtReverseTs { get; set; }
        public string? RphaseCtOpen { get; set; }
        public string? RphaseCtOpenTs { get; set; }
        public string? YphaseCtOpen { get; set; }
        public string? YphaseCtOpenTs { get; set; }
        public string? BphaseCtOpen { get; set; }
        public string? BphaseCtOpenTs { get; set; }
        public string? CurrentUnbalance { get; set; }
        public string? CurrentUnbalanceTs { get; set; }
        public string? CtBypass { get; set; }
        public string? CtBypassTs { get; set; }
        public string? OverCurrentPhase { get; set; }
        public string? OverCurrentPhaseTs { get; set; }
        public string? PowerFailure { get; set; }
        public string? PowerFailureTs { get; set; }
        public string? DateAndTimeChanged { get; set; }
        public string? DateAndTimeChangedTs { get; set; }
        public string? DemandIntegrationPeriodChanged { get; set; }
        public string? DemandIntegrationPeriodChangedTs { get; set; }
        public string? ProfileCapturePeriodChanged { get; set; }
        public string? ProfileCapturePeriodChangedTs { get; set; }
        public string? BillingDateChanged { get; set; }
        public string? BillingDateChangedTs { get; set; }
        public string? TimeZonesChanged { get; set; }
        public string? TimeZonesChangedTs { get; set; }
        public string? NewFirmwareActivated { get; set; }
        public string? NewFirmwareActivatedTs { get; set; }
        public string? LlsSecretMrChange { get; set; }
        public string? LlsSecretMrChangeTs { get; set; }
        public string? HlsKeyUsChange { get; set; }
        public string? HlsKeyUsChangeTs { get; set; }
        public string? HlsKeyFwChange { get; set; }
        public string? HlsKeyFwChangeTs { get; set; }
        public string? GlobalKeyChange { get; set; }
        public string? GlobalKeyChangeTs { get; set; }
        public string? EventRegisterChanged { get; set; }
        public string? EventRegisterChangedTs { get; set; }
        public string? MdReset { get; set; }
        public string? MdResetTs { get; set; }
        public string? MeteringModeChanged { get; set; }
        public string? MeteringModeChangedTs { get; set; }
        public string? ImageActivationDateAndTimeChanged { get; set; }
        public string? ImageActivationDateAndTimeChangedTs { get; set; }
        public string? ConfigurationChangeToForwardedModeOnlyMode { get; set; }
        public string? ConfigurationChangeToForwardedModeOnlyModeTs { get; set; }
        public string? ConfigurationChangeToImportExportMode { get; set; }
        public string? ConfigurationChangeToImportExportModeTs { get; set; }
        public string? RphaseContactorCoilSupplyOnAlert { get; set; }
        public string? RphaseContactorCoilSupplyOnAlertTs { get; set; }
        public string? RelayAlertTs { get; set; }
        public string? SrlcBypassAlert { get; set; }
        public string? SrlcBypassAlertTs { get; set; }
        public string? TmdsDoorAlert { get; set; }
        public string? TmdsDoorAlertTs { get; set; }
        public string? TerminalAlert { get; set; }
        public string? TerminalAlertTs { get; set; }
        public string? SrlcCoverAlert { get; set; }
        public string? SrlcCoverAlertTs { get; set; }
        public string? PowerAlertTs { get; set; }
        public string? AbnormalExternalMagnetInfluence { get; set; }
        public string? AbnormalExternalMagnetInfluenceTs { get; set; }
        public string? NeutralDisturbance { get; set; }
        public string? NeutralDisturbanceTs { get; set; }
        public string? LowPf { get; set; }
        public string? LowPfTs { get; set; }
        public string? CommunicationModule { get; set; }
        public string? CommunicationModuleTs { get; set; }
        public string? Overload { get; set; }
        public string? OverloadTs { get; set; }
        public string? MeterCoverOpening { get; set; }
        public string? MeterCoverOpeningTs { get; set; }
        public string? LoadSwitch { get; set; }
        public string? LoadSwitchTs { get; set; }
        public string? OilLevelTs { get; set; }
        public string? OilTemperature { get; set; }
        public string? OilTemperatureTs { get; set; }
        public string? SurfaceTemperature { get; set; }
        public string? SurfaceTemperatureTs { get; set; }
        public string? AmbTemperature { get; set; }
        public string? AmbTemperatureTs { get; set; }
        public string? ContactorAlert { get; set; }
        public string? ContactorAlertTs { get; set; }
        public string? BphaseContactorCoilSupplyAlert { get; set; }
        public string? BphaseContactorCoilSupplyAlertTs { get; set; }
        public string? RphaseContactorCoilSupplyAlert { get; set; }
        public string? RphaseContactorCoilSupplyAlertTs { get; set; }
        public int? SrlcdeviceId { get; set; }
        public string? SrlceventTimestamp { get; set; }
        public string? SrlceventId { get; set; }
        public string? SrlcconnectStatus { get; set; }
        public long? SrlccumulativeEventcounter { get; set; }
        public string? SrlccontrolMode { get; set; }
        public string? SrlceventStatusWord { get; set; }
        public string? Dip { get; set; }
        public string? ProfileCapturePeriod { get; set; }
        public decimal? NetEnergykWh { get; set; }
        public decimal? NetEnergykVarhLag { get; set; }
        public decimal? NetEnergykVarhLead { get; set; }
        public decimal? NetEnergykVah { get; set; }
        public decimal? MaximumDemandkWimport { get; set; }
        public decimal? MaximumDemandkVaimport { get; set; }
        public string? TypeOfBillReset { get; set; }
        public string? SizeExecutionTime { get; set; }
        public string? EventRegisterStatus { get; set; }
        public DateTimeOffset Sts { get; set; }
        public string? LocalRemote { get; set; }
        public string? SetResponse { get; set; }
        public string? Srlcversion { get; set; }
        public string? SrlcyearofManufacture { get; set; }
        public string? ActionEnableDisablebitdescription { get; set; }
        public string? BlockLoadInterval { get; set; }
        public string? EnableDisable { get; set; }
        public string? OilTemperatureCalibration { get; set; }
        public string? SurfaceTemperatureCalibration { get; set; }
        public string? AmbientTemperatureCalibration { get; set; }
        public string? OilTemperatureThresholdHigh { get; set; }
        public string? SurfaceTemperatureThresholdHigh { get; set; }
        public string? AmbientTemperatureThresholdHigh { get; set; }
        public string? OilTemperatureThresholdMedium { get; set; }
        public string? SurfaceTemperatureThresholdMedium { get; set; }
        public string? AmbientTemperatureThresholdMedium { get; set; }
        public string? Time { get; set; }
        public string? Date { get; set; }
        public bool? IsDataExist { get; set; }
        public decimal? OilTempHighOccurrence { get; set; }
        public int? OilTempHighOccurencePersistance { get; set; }
        public decimal? OilTempHighRestoration { get; set; }
        public int? OilTempHighRestorationPersistance { get; set; }
        public string? ActionAtOilTemp { get; set; }
        public decimal? SurafaceTempHighOccurrence { get; set; }
        public int? SurfaceTempHighOccurencePersistance { get; set; }
        public decimal? SurfaceTempHighRestoration { get; set; }
        public int? SurfaceTempHighRestorationPersistance { get; set; }
        public string? ActionAtSurfaceTemp { get; set; }
        public decimal? AmbtempHighOccurrence { get; set; }
        public int? AmbtempHighOccurencePersistance { get; set; }
        public decimal? AmbtempHighRestoration { get; set; }
        public int? AmbtempHighRestorationPersistance { get; set; }
        public string? ActionAtAmbtemp { get; set; }
        public decimal? OilTempMediumOccurrence { get; set; }
        public int? OilTempMediumOccurencePersistance { get; set; }
        public decimal? OilTempMediumRestoration { get; set; }
        public int? OilTempMediumRestorationPersistance { get; set; }
        public string? ActionAtOilTempMedium { get; set; }
        public decimal? SurafaceTempMediumOccurrence { get; set; }
        public int? SurfaceTempMediumOccurencePersistance { get; set; }
        public decimal? SurfaceTempMediumRestoration { get; set; }
        public int? SurfaceTempMediunRestorationPersistance { get; set; }
        public string? ActionAtSurfaceTempMedium { get; set; }
        public decimal? AmbtempMediumOccurrence { get; set; }
        public int? AmbtempMediumOccurencePersistance { get; set; }
        public decimal? AmbtempMediumRestoration { get; set; }
        public int? AmbtempMediumRestorationPersistance { get; set; }
        public string? ActionAtAmbtempMedium { get; set; }
        public decimal? ActivePowerImport { get; set; }
        public string? Channel0SumLiActivePowerQ1q4minusQ2q3timeIntegral { get; set; }
        public string? Channel0L1reactivePowerQ1q2timeIntegral { get; set; }
        public string? Channel0L3reactivePowerQ1q2timeIntegral { get; set; }
        public string? Channel0L2apparentPowerQ1q4timeIntegral { get; set; }
        public string? Channel0L0currentNeutralAvgCurrent { get; set; }
        public string? Channel0SumLiActivePowerQ1q4max { get; set; }
        public string? Channel0SumLiApparentPowerQ1q4max { get; set; }
    }
}
